version: '2.1'
services:
  db:
    container_name: pomorint-nestjs-db
    image: postgres
    environment:
      POSTGRES_USER: pomo-rint
      POSTGRES_PASSWORD: pomorint
      POSTGRES_ROOT_PASSWORD: pomorint
    volumes_from:
      - data
    ports:
      - 5432:5432

#  cache:
#    container_name: pomorint-nestjs-cache
#    image: redis
#    ports:
#    - 6379:6379

  data:
    container_name: pomorint-nestjs-data
    image: busybox
    volumes:
    - /var/lib/postgresql/data
